---
ID: "caf39d4e-d6ee-4714-979d-82f5bf6cf692"
Parent: "fb2e9334-a081-48c2-9131-743f3044cefc"
Template: "e46f3af2-39fa-4866-a157-7017c4b2a40c"
Path: /sitecore/content/Verticals/Services/Settings/Site Grouping/Services
SharedFields:
- ID: "1ee576af-ba8e-4312-9fbd-2ccf8395baa1"
  Hint: StartItem
  Value: "{57F2E85D-D695-4E6C-8C89-947CE5443E2E}"
- ID: "6dd8a774-2ce5-4c9e-be7f-1eaf65789956"
  Hint: ThumbnailsRootPath
  Value: /sitecore/media library/Project/Verticals/Services
- ID: "85a7501a-86d9-4243-9075-0b727c3a6db4"
  Hint: Name
  Value: Services
- ID: "8e0dd914-9afb-4d45-bf8b-7ff5d6e5337e"
  Hint: HostName
  Value: "adotest-ockiyewrtectxmpr2upeq-Services.vercel.app"
- ID: "cb4e9e2e-2b66-43dc-ad3f-9caf363d28d3"
  Hint: SiteName
  Value: Services
- ID: "da06d09e-02b6-464a-80fc-9d8d7fc875e3"
  Hint: Environment
  Value: *
- ID: "f57099a3-526a-49f2-aebd-635453e48875"
  Hint: RenderingHost
  Value: Default
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{23E42340-77BE-49FC-A7C4-77D3CB545223}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240227T211037Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\alexander.doroshenko@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\alexander.doroshenko@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "46325c03-e03c-4516-b164-3a561f028df2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\GaHzzAzGnTg8xtS0ynYCao6Mfo42yEpO
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240301T184828Z
